package runtime_exceptions;

public class Main {

	public static void main(String[] args) {

		/*
		 * ArithmeticException
		 * 
		 * int a = 23/0; System.out.println(a);
		 */

		/*
		 * NullPointerException
		 * 
		 * String text = null; System.out.println(text.length());
		 */

		/*
		 * ArrayIndexOutOfBoundsException
		 * 
		 * int numbers[] = new int[7]; numbers[9] = 58;
		 */

		/*
		 * NumberFormatException
		 * 
		 * String text = "Text"; int number = Integer.parseInt(text);
		 */
		
		/*
		 * try { System.out.println("rest of the code1");
		 *  int value = 87 / 0;
		 * System.out.println("rest of the code2");
		 *  } catch (ArithmeticException e) {
		 * System.out.println(e);
		 *  }
		 *   System.out.println("rest of the code3");
		 */
		
		
	}

}
